### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by acelaya** [phly/phly-event-dispatcher#5]
- [ ] I was not able to find an [open](https://github.com/phly/event-dispatcher/issues?q=is%3Aopen) or [closed](https://github.com/phly/event-dispatcher/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [ ] This is not a question.

Are you open to add PHP 8 support to this library?

I'm open to contribute the change if so.

**Comment by weierophinney** [comment]
Completed with release 1.1.0 (release 2021-11-15).
